export type { OtterItem, Item, Edge, Clause, Literal, OtterState, OtterDomain, StepRecord, Volatile, Fluid, Salt, Alkahest } from "./types.js"
export { otterStep, runOtter } from "./engine.js"
export { makeItem, makeEdge, makeClause } from "./items.js"
export type { PhaseMarker, ThermalNode, ThermalEdge, ThermalGraph, EffectivePhase, HeatEventKind, ChangelogEvent, ThermalSnapshot } from "./thermal.js"
export { effectivePhase, defaultThresholds, emitHeat, propagate, thermalStep, buildThermalGraph, snapshot } from "./thermal.js"
